/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xuzhang' at '1/21/16 12:33 PM' with Gradle 2.2.1
 *
 * @author xuzhang, @date 1/21/16 12:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
